import os
import sqlite3
from typing import List

DATABASE_URL = (os.getenv("DATABASE_URL") or "").strip()
SQLITE_PATH = (os.getenv("SQLITE_PATH") or "bookings.db").strip()
_USE_SQLITE_FALLBACK = False


def is_postgres() -> bool:
    return (not _USE_SQLITE_FALLBACK) and (
        DATABASE_URL.startswith("postgresql://") or DATABASE_URL.startswith("postgres://")
    )


def get_conn():
    global _USE_SQLITE_FALLBACK
    if DATABASE_URL and not _USE_SQLITE_FALLBACK:
        try:
            import psycopg  # type: ignore
            connect_timeout = int((os.getenv("PG_CONNECT_TIMEOUT") or "4").strip() or "4")

            # Disable prepared statements to avoid PgBouncer/Supabase
            # transaction-pool errors like:
            # DuplicatePreparedStatement: prepared statement "_pg3_0" already exists
            return psycopg.connect(
                DATABASE_URL,
                prepare_threshold=None,
                connect_timeout=max(2, connect_timeout),
            )
        except Exception:
            # Keep the app usable if hosted Postgres has a transient outage.
            _USE_SQLITE_FALLBACK = True
    return sqlite3.connect(SQLITE_PATH, check_same_thread=False)


def adapt_query(query: str) -> str:
    if is_postgres():
        return query.replace("?", "%s")
    return query


def execute(cur, query: str, params=()):
    return cur.execute(adapt_query(query), params)


def executemany(cur, query: str, params_list):
    return cur.executemany(adapt_query(query), params_list)


def id_pk_col() -> str:
    if is_postgres():
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def list_columns(conn, table: str) -> List[str]:
    if is_postgres():
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema='public' AND table_name=%s
                """,
                (table,),
            )
            return [r[0] for r in cur.fetchall()]
    cur = conn.cursor()
    cur.execute(f"PRAGMA table_info({table})")
    return [r[1] for r in cur.fetchall()]


def ensure_column(conn, table: str, column: str, col_type_sql: str):
    cols = list_columns(conn, table)
    if column in cols:
        return
    cur = conn.cursor()
    if is_postgres():
        cur.execute(f'ALTER TABLE "{table}" ADD COLUMN IF NOT EXISTS "{column}" {col_type_sql}')
    else:
        cur.execute(f"ALTER TABLE {table} ADD COLUMN {column} {col_type_sql}")
    conn.commit()
