#!/usr/bin/env python3
import argparse
import os
import sqlite3
from typing import Dict, List, Tuple


def map_sqlite_type_to_pg(sqlite_type: str) -> str:
    t = (sqlite_type or "").upper()
    if "INT" in t:
        return "BIGINT"
    if "REAL" in t or "FLOA" in t or "DOUB" in t:
        return "DOUBLE PRECISION"
    if "BLOB" in t:
        return "BYTEA"
    return "TEXT"


def normalize_default(default_val: str) -> str:
    if default_val is None:
        return ""
    raw = str(default_val).strip()
    if raw == "":
        return ""
    # Keep quoted literals and numeric defaults as-is.
    return f" DEFAULT {raw}"


def table_columns(sqlite_conn: sqlite3.Connection, table: str) -> List[Tuple]:
    cur = sqlite_conn.cursor()
    cur.execute(f"PRAGMA table_info({table})")
    return cur.fetchall()


def sqlite_tables(sqlite_conn: sqlite3.Connection) -> List[str]:
    cur = sqlite_conn.cursor()
    cur.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type='table' AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    )
    return [r[0] for r in cur.fetchall()]


def create_pg_table(pg_conn, table: str, cols: List[Tuple]) -> None:
    # PRAGMA table_info tuple:
    # (cid, name, type, notnull, dflt_value, pk)
    col_defs = []
    pkeys = []
    for _, name, ctype, notnull, dflt, pk in cols:
        pg_type = map_sqlite_type_to_pg(ctype)
        if int(pk or 0) == 1 and pg_type == "BIGINT":
            col_defs.append(f'"{name}" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
        else:
            not_null_clause = " NOT NULL" if int(notnull or 0) == 1 else ""
            default_clause = normalize_default(dflt)
            col_defs.append(f'"{name}" {pg_type}{not_null_clause}{default_clause}')
            if int(pk or 0) == 1:
                pkeys.append(name)

    pk_clause = ""
    if pkeys:
        pk_cols = ", ".join([f'"{c}"' for c in pkeys])
        pk_clause = f", PRIMARY KEY ({pk_cols})"

    ddl = f'CREATE TABLE IF NOT EXISTS "{table}" ({", ".join(col_defs)}{pk_clause})'
    with pg_conn.cursor() as cur:
        cur.execute(ddl)
    pg_conn.commit()


def copy_table(sqlite_conn: sqlite3.Connection, pg_conn, table: str, cols: List[Tuple]) -> int:
    col_names = [c[1] for c in cols]
    if not col_names:
        return 0

    src_cur = sqlite_conn.cursor()
    select_cols = ", ".join([f'"{c}"' for c in col_names])
    src_cur.execute(f'SELECT {select_cols} FROM "{table}"')
    rows = src_cur.fetchall()

    with pg_conn.cursor() as cur:
        cur.execute(f'TRUNCATE TABLE "{table}" RESTART IDENTITY')
        if rows:
            placeholders = ", ".join(["%s"] * len(col_names))
            col_sql = ", ".join([f'"{c}"' for c in col_names])
            cur.executemany(
                f'INSERT INTO "{table}" ({col_sql}) VALUES ({placeholders})',
                rows,
            )
    pg_conn.commit()
    return len(rows)


def migrate(sqlite_path: str, postgres_url: str) -> None:
    try:
        import psycopg  # type: ignore
    except Exception as e:
        raise SystemExit(f"Missing dependency 'psycopg'. Install with: pip install psycopg[binary]. Error: {e}")

    if not os.path.exists(sqlite_path):
        raise FileNotFoundError(f"SQLite file not found: {sqlite_path}")

    sqlite_conn = sqlite3.connect(sqlite_path)
    sqlite_conn.row_factory = sqlite3.Row

    with psycopg.connect(postgres_url) as pg_conn:
        tables = sqlite_tables(sqlite_conn)
        if not tables:
            print("No SQLite tables found.")
            return

        print(f"Found {len(tables)} tables: {', '.join(tables)}")
        total_rows = 0
        for table in tables:
            cols = table_columns(sqlite_conn, table)
            create_pg_table(pg_conn, table, cols)
            row_count = copy_table(sqlite_conn, pg_conn, table, cols)
            total_rows += row_count
            print(f"Migrated table '{table}': {row_count} rows")

        print(f"Migration complete. Total rows copied: {total_rows}")

    sqlite_conn.close()


def main():
    parser = argparse.ArgumentParser(description="Migrate SQLite DB to PostgreSQL")
    parser.add_argument("--sqlite-path", default="bookings.db", help="Path to SQLite DB file")
    parser.add_argument("--postgres-url", default=os.getenv("DATABASE_URL", ""), help="Postgres connection URL")
    args = parser.parse_args()

    if not args.postgres_url:
        raise SystemExit("Missing --postgres-url or DATABASE_URL")

    migrate(args.sqlite_path, args.postgres_url)


if __name__ == "__main__":
    main()
